main:
	gcc -Wall -pedantic -std=gnu99 -g stlucia.c -o stlucia
	gcc -Wall -pedantic -std=gnu99 -g player.c -o EAIT -D EAIT
	gcc -Wall -pedantic -std=gnu99 -g player.c -o SCIENCE -D SCIENCE
	gcc -Wall -pedantic -std=gnu99 -g player.c -o HASS -D HASS
	gcc -Wall -pedantic -std=gnu99 -g player.c -o MABS -D MABS
